export const levelOne = [
  "What was the first thing you noticed about me?",
  "What do you think is the hardest part of what I do for a living?",
  "What do you think my perfect date night would be?",
  "Who do you think was more nervous on our first 'date(s)'?",
  "What assumption did you make about me that turned out to be false?",
  "Do I seem like more of a creative or analytical type? Explain.",
  "On a scale of 1-10, how open do you feel I am with you?",
  "What would the person closest to you describe you in three words?",
  "What was your first impression of me?",
  "If you were to buy me a present, knowing nothing about me other than what I look like, what would it be?",
  "What character would I play in a movie?",
  "Do I remind you of anyone?",
  "Do I look kind? Explain.",
  "Do you think I've ever checked an ex's phone for evidence?",
  "What about me intrigues you?",
  "How would you describe what you think my type is in three words?",
  "What do you think my go-to karaoke song is?",
  "If you were to buy me a present, knowing nothing about me other than what I look like, what would it be?",
  "What's something you dislike that most people don't?",
  "Do I look kind? explain.",
  "Do you think I fall in love easily? Why or why not?",
  "As a child, what do you think I wanted to be?",
  "Do you think I'm usually early, on time, or late to events? explain.",
  "What subject do you think I thrived in at school? Did I fail any?",
  "What compliment do you think I hear the most?",
  "Do you have a favourite picture of me?",
  "What is my body language telling you right now?",
  "Do you think I intimidate others? Why or why not?",
  "What about me is most strange or unfamiliar to you?",
  "If Myspace were still a thing, what would my profile song be?",
  "What is the worst assumption someone has made about you?",
];

export const levelTwo = [
  "What is your defining characteristic?",
  "What's been the hardest part of all this for you? Permission to vent.",
  "What are you better at than most people you know? Permission to brag.",
  "Wildcard: Both write down the three most important things to you in a relationship. Compare.",
  "Wildcard: Both write down a dating pet peeve. Compare",
  "What have I tolerated from people in the past that I no longer have space for?",
  "Something that brought a smile to my face this week was ___.",
  "What do you believe is the best thing about us?",
  "What is the sexiest thing I've said/done to you?",
  "What is something you want to do together but we haven't done yet?",
  "What is the most comforting thing I've ever done for you?",
  "What's the most unexpected thing you've learned about me?",
  "What is your most toxic trait you can admit to?",
  "What is one thing about us you never want to change?",
  "What are you overthinking right now?",
  "Is there anything I've stopped doing that you miss/used to like?",
  "What's the most romantic thing I've done for you recently?",
  "What do you need to forgive yourself for?",
  "What's the most attractive thing I do without realising it?",
  "What immediately attracted you to me? What attracted you more over time?",
  "What have I helped you appreciate about yourself?",
  "Wildcard: Ask your partner something you've never asked them before.",
  "How does our age difference, or lack thereof, affect us? If at all?",
  "Think of someone you admire. Why did this person come to mind?",
  "Are you lying to yourself about anything?",
  "What's your favorite part of yourself that isn't physical?",
  "What's the hardest part about dating you?",
  "What's your favorite song lyric you can think of off the top of your head?",
  "What's the best lesson an ex has ever taught you?",
  "What's a value that guides your decision-making?",
  "When was the last time you felt lucky to be you?",
  "What's something small that consistently brings you joy?",
  "What would your younger self not believe about your life today?",
  "What's a belief you had 5 years ago that you've since changed?",
  "What dating advice would you give your younger self?",
  "What lesson should you have learned by now?",
  "What would you never want to change about yourself?",
  "Finish the sentences: strangers would describe me as _____. Only I know that I am ______",
  "When you're asked how you are, how often do you answer truthfully?",
  "What is the most unexplainable thing that's ever happened to you?",
  "Describe your perfect day!",
  "What's been the best compliment a stranger has ever given you?",
  "What is a compliment you wish you received more frequently?",
  "When was the last time you surprised yourself?",
  "What's been your happiest memory this past year?",
  "If you have, when was the moment you realised you weren't invincible?",
  "What is a dream you've let go of?",
  "What is the last thing you lied to your mother about?",
 " If we were in a band, what would our name be?",
  "Have you ever told someone I love you but didn't mean it? if so, why?",
];

export const levelThree = [
  "What don't I give myself enough credit for?",
  "Is there anything you still don't know about me that you wish you did?",
  "What answer of mine surprised you the most throughout this game? If any?",
  "In a word, how would you describe our conversation?",
  "What do you think my strength is?",
  "What can I teach you?",
  "Based on what you've learned about me, do you have any movie recommendations?",
  "What about our relationship are you proudest of?",
  "Thank you for helping me realise _____ about myself.",
  "What do you think my weakness is?",
  "What parts of yourself do you see in me?",
  "How would you describe me to a stranger?",
  "What answer of mine made you light up?",
  "What would be the perfect gift for me?",
  "What do you admire most about me?",
  "What's the most attractive quality about me that isn't physical?",
  "What about me is hardest for you to understand?",
  "What am I most qualified to give advice about?",
  "What is one thing you think I can do that would dramatically improve my life?",
  "What's one part of your personality you do not use often?",
  "Based on what you learned about me, does my social media accurately reflect who I am? Why or why not?",
  "What do I need to hear right now?",
  "What's something you've never said out loud but often think about?",
  "What do you think I should know about myself that perhaps I'm unaware of?",
  "In what ways are you different from the version of yourself a year ago?",
  "How does one earn your trust? Have I earned it? How can I earn more?",
  "What do you think our most important similarity is?",
  "When this game is over, what will you remember about me?",
  "What question were you most afraid to answer?",
  "How do our personalities complement each other?",
  "What do you think my defining characteristic is?",
  "Do you believe everyone has a calling? If so, do you think I've found mine?",
];
